CREATE TABLE leads (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  nome VARCHAR(150) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  valor VARCHAR(30) NOT NULL,
  prazo VARCHAR(50) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  profissao VARCHAR(100) NOT NULL,
  renda VARCHAR(10) NOT NULL,
  conta VARCHAR(10) NOT NULL,
  mensagem_extra TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);